# --------------------------
# HTTP 80 → HTTPS 重定向
# 配置文件位置：/etc/nginx/conf.d/default.conf
# --------------------------
server {
    if ($host = www.mlinyun.com) {
        return 301 https://$host$request_uri;
    }

    if ($host = user-center.mlinyun.com) {
        return 301 https://$host$request_uri;
    }

    if ($host = mlinyun.com) {
        return 301 https://$host$request_uri;
    }

    listen 80;
    server_name mlinyun.com www.mlinyun.com user-center.mlinyun.com;

    # 所有 HTTP 请求统一重定向到 HTTPS
    return 301 https://$host$request_uri;
}