# --------------------------
# 子域名 docs.uc 凌云用户中心系统文档静态站点 Nginx 配置
# 配置文件位置：/etc/nginx/conf.d/user-center-docs.conf
# --------------------------
server {
    listen 443 ssl;
    server_name docs.uc.example.com;

    index index.html;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        # 内容位置
        root /var/www/user-center/user-center-docs;

        # 完全匹配 -> 反向清理 url -> 文件夹 -> 没有发现
        try_files $uri $uri.html $uri/ =404;

        # 不存在的页面
        error_page 404 /404.html;

        # 在此设置中，如果文件夹没有 index.html，就会引发 403 错误
        error_page 403 /404.html;

        # 调整缓存标头
        # assets 文件夹中的文件都有哈希文件名
        location ~* ^/assets/ {
            expires 1y;
            add_header Cache-Control "public, immutable";
        }
    }
}