spring:
  application:
    # Spring Boot 项目名称
    name: user-center-backend
  profiles:
    # 默认激活的配置文件
    active: dev
  datasource:
    # MySQL 驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    # Session 失效时间，单位为秒（1天）
    timeout: 86400
  servlet:
    multipart:
      # 开启文件上传
      enabled: true
      # 单个文件最大大小
      max-file-size: 2MB
      # 单次请求最大大小
      max-request-size: 10MB

# 文件上传配置
file:
  upload:
    # 文件上传根目录
    upload-dir: ./uploads
    # 头像上传子目录
    avatar-dir: avatar
    # 允许的文件类型
    allowed-types: image/jpeg,image/png,image/jpg,image/gif
    # 最大文件大小（字节）2MB
    max-size: 2097152
    # 访问路径前缀
    access-prefix: http://localhost:8100/api/file

# 服务器配置
server:
  port: 8100
  servlet:
    # 应用上下文路径
    context-path: /api

# 日志配置
logging:
  file:
    # 日志文件路径
    name: logs/user-center-backend.log
  level:
    # 全局日志级别
    root: info
  logback:
    rollingpolicy:
      # 日志文件存档的最大数量
      max-history: 2000
      # 单个日志文件最大大小
      max-file-size: 5MB

# MyBatis-Plus 配置
mybatis-plus:
  configuration:
    # 开启驼峰命名映射
    map-underscore-to-camel-case: true
    # 使用标准输出来记录 SQL 执行日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # Mapper XML 文件路径
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.mlinyun.usercenter.model
  global-config:
    # 启用 SQL 运行器
    enable-sql-runner: true
    db-config:
      # 设置全局逻辑删除实体字段名
      logic-delete-field: isDeleted
      # 逻辑未删除值
      logic-not-delete-value: 0
      # 逻辑已删除值
      logic-delete-value: 1

# Swagger 配置
springdoc:
  swagger-ui:
    # 自定义Swagger UI HTML 的访问路径
    path: /swagger-ui.html
    # 设置 Swagger UI 中的标签按字母顺序排序
    tags-sorter: alpha
    # 设置 Swagger UI 中的接口按字母顺序排序
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs

# Knife4j 配置
knife4j:
  # 开启 Knife4j 增强模式
  enable: true
  setting:
    # 设置 Knife4j 的界面语言为中文
    language: zh_cn
  basic:
    # 开启 BasicHttp 校验，保护文档
    enable: true
    username: admin
    password: admin123
