spring:
  datasource:
    url: jdbc:mysql://prod-db-host:3306/user_center?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}

logging:
  level:
    root: info

knife4j:
  # 生产环境
  production: true
